name: Runner
main: ch.toothwit.runner.main.Runner
version: 1.0
author: fredo121
description: Runner Plugin using Spigot API 
depend: [BarAPI,Lobby]

commands:
  runner:
    description: Runner Base Command
    permission: runner.use
    
permissions:
  runner.use:
    description: Use Runner Commands
    default: true
  runner.admin:
    description: Use Runner Admin Commands
    default: op